name: ryanclbryant
favicon: null
layout_spectrum: 0.90648656594567
typography_spectrum: 0.9590336424298584
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5630101326387376
  lightness: 0.21767703373916447
  saturation: 0.684160994598642
  rhythmicContrast: 0.4344912136439234
purpose: []
