analytics:
  twitter: null
  google: UA-77255350-1
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.8949
title: Ryan Bryant
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.684160994598642
  brandStrength: 0.5630101326387376
  rhythmicContrast: 0.4344912136439234
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  lightness: 0.2176770337391645
purpose: []
favicon: null
name: ryanclbryant
typography_spectrum: 0.84866
